name: Build Godot Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: ${{ vars.GODOT_VERSION }}
  PROJECT_PATH: ${{ vars.PROJECT_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [Windows, Linux]

    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
      options: --memory=6g

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup export templates
      run: |
        mkdir -p ~/.local/share/godot/export_templates/
        cp -r /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        pwd && ls -lah ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

    - name: Build project
      run: |
        mkdir -p build/${{ matrix.platform }}
        pwd && ls -lah
        ls -lah build/
        cd ${{ env.PROJECT_PATH }}
        if [ "${{ matrix.platform }}" = "Windows" ]; then
          godot --headless --verbose --export-release "Windows Desktop" "build/Windows/Seconds of Eternity.exe"
        else
          godot --headless --verbose --export-release "Linux" "build/Linux/Seconds of Eternity.x86_64"
        fi
    - name: Upload ${{ matrix.platform }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-build
        path: build/${{ matrix.platform }}